---
- hosts: all
  name: Install required software
  become: yes
  tasks:
    - name: Install packages 
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - apache2
          - php
          - php-xml
    #run command - sudo wget https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
    - name: Unarchive dokuwiki
      ansible.builtin.unarchive:
        src: dokuwiki-stable.tgz
        dest: /var/www/html/
